---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-clustergroup-prod-utilities
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./environments/demo-clustergroup-prod/utilities
  prune: true
  sourceRef:
    kind: GitRepository
    name: tmc-git-repo
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: contour
      namespace: tanzu-system-ingress      